# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

x = 1
y = 2
res = 2
fibo = x + y

while fibo < 4000000:
    fibo = x + y
    if not fibo % 2:
        res += fibo
    x = y
    y = fibo

print(res)